language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g spago purescript
  - npm install
  - spago build
script:
  - npm run -s build
  - spago build
  - npm -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
